#!/usr/bin/env bash
# Ignore shellcheck SC2086

domain=$1
subdomain=$2

# Function to get DNS info
get_dns_info() {
    local sub=$1

    result=$(dig $sub.$domain | awk '/ANSWER SECTION:/ {getline; print}')

    record_type=$(echo $result | awk '{print $4}')
    destination=$(echo $result | awk '{print $5}')

    echo "The subdomain $sub is a $record_type record and points to $destination"
}

# If subdomain is provided
if [ -n "$subdomain" ]; then
    get_dns_info $subdomain
else
    # Default subdomains in order
    for sub in www lb-01 web-01 web-02
    do
        get_dns_info $sub
    done
fi
